# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de0af9034672f0df848e857668c21d342604a599a453de1f2610244ca029331c2f51f1dbb42b45ef12d0940d8348a6e5787d2b70f08313f00db58b931ac6706e

test:
  secret_key_base: 6a9a0f3641ed180611ec8572c2b781a465c60dd08ab0c5b4cef5dc0c3152e77b1ac24e8e1ea7a32d556382f475403ff651f986d12960d7269c235f011b02bcbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
